### PR TITLE
Feature/compiletime di

### PR DESCRIPTION
**Pull request by lloydmeta**
- Bump Play version to 2.3.9 (we are not affected by the cookie issue)
- Remove Scaldi, switch to Macwire for sanity.

### CODE REVIEW

**Comment by seratch** [comment]
Will you keep using Macwire when upgrading to Play 2.4? (I'm just curious)
https://github.com/adamw/macwire#play-24x-

**Comment by lloydmeta** [comment]
Currently, that is the plan.

**Comment by seratch** [comment]
Thanks. Are there any known blocker issues that prevent Octoparts' Play 2.4 upgrade?

**Comment by lloydmeta** [comment]
None at the moment, @mauhiz informed me that there are now fallbacks for the JSON serdes-related functionality, so I intend to work on that right after this is finished.

**Comment by mauhiz** [comment]
@seratch AFAIK, we can do it if we don't couple it to the scala client upgrade.

**Comment by mauhiz** [comment]
LGTM

**Pull request merged**
