### PR TITLE
Feature/tryit contents

### LINKED ISSUE #69: "Try it!" page should allow inputting parameters with multiple values

### PR DESCRIPTION
**Pull request by mauhiz**
- clean output of part response and its contents, with syntax highlighting
- support for multiple parameter values
- do not allow required parameters to be disabled

Fixes #69

### CODE REVIEW

**Comment by lloydmeta** [comment]
Looks like nice enhancements to have :) 

It would be nice to have someone with better JS-foo than I look at this to make double sure we won't be on the receiving end of simple injection attacks; @seratch can you please chime in?

**Comment by seratch** [comment]
Sorry for missing this. This looks fine to me.

**Comment by lloydmeta** [comment]
Can you please rebase this ?

**Comment by mauhiz** [comment]
made it mergeable, and removed the annoying async=false

**Comment by lloydmeta** [comment]
Cool, LGTM, please merge after Travis gives us green.

**Pull request merged**
