### PR TITLE
Closes #194 Make Play-app harnesses extend from RequiresDB

### LINKED ISSUE #194: Connection pool tests consistently failing
The bottom result is from `testOnly com.m3.octoparts.database.MigrationsSpec` but the following failed:

```
[info] *** 1 SUITE ABORTED ***
[info] *** 3 TESTS FAILED ***
[error] Error: Total 290, Failed 3, Errors 1, Passed 286
[error] Failed tests:
[error]     com.m3.octoparts.future.RichFutureWithTimingSpec
[error]     com.m3.octoparts.database.MigrationsSpec
[error] Error during tests:
[error]     com.m3.octoparts.repository.config.CacheGroupRepositorySpec
[error] (octoparts/test:test) sbt.TestsFailedException: Tests unsuccessful
```

This is running tests from within vaygrant, and from without. In neither case was Octoparts running in the background in a separate terminal.

```
[info] MigrationsSpec:
[info] Running migrations
[info]   from an empty database
2016-02-08 05:32:31,402 ERROR [pool-1-thread-1-ScalaTest-running-MigrationsSpec] application [RequiresDB.scala:79] 
java.lang.IllegalStateException: Connection pool is not yet initialized.(name:'default)
    at scalikejdbc.ConnectionPool$$anonfun$get$1.apply(ConnectionPool.scala:57) ~[scalikejdbc-core_2.11-2.3.0.jar:2.3.0]
    at scalikejdbc.ConnectionPool$$anonfun$get$1.apply(ConnectionPool.scala:55) ~[scalikejdbc-core_2.11-2.3.0.jar:2.3.0]
    at scala.Option.getOrElse(Option.scala:121) ~[scala-library-2.11.7.jar:na]
    at scalikejdbc.ConnectionPool$.get(ConnectionPool.scala:55) ~[scalikejdbc-core_2.11-2.3.0.jar:2.3.0]
    at scalikejdbc.ConnectionPool$.apply(ConnectionPool.scala:46) ~[scalikejdbc-core_2.11-2.3.0.jar:2.3.0]
    at com.m3.octoparts.support.db.RequiresDB$class.flyway(RequiresDB.scala:57) ~[test-classes/:na]
    at com.m3.octoparts.database.MigrationsSpec.flyway$lzycompute(MigrationsSpec.scala:6) [test-classes/:na]
    at com.m3.octoparts.database.MigrationsSpec.flyway(MigrationsSpec.scala:6) [test-classes/:na]
    at com.m3.octoparts.support.db.RequiresDB$class.tearDown(RequiresDB.scala:77) ~[test-classes/:na]
    at com.m3.octoparts.database.MigrationsSpec.tearDown(MigrationsSpec.scala:6) [test-classes/:na]
    at com.m3.octoparts.database.MigrationsSpec$$anonfun$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcV$sp$2.apply$mcV$sp(MigrationsSpec.scala:11) [test-classes/:na]
    at com.m3.octoparts.database.MigrationsSpec$$anonfun$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcV$sp$2.apply(MigrationsSpec.scala:10) [test-classes/:na]
    at com.m3.octoparts.database.MigrationsSpec$$anonfun$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcV$sp$2.apply(MigrationsSpec.scala:10) [test-classes/:na]
    at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22) [scalatest_2.11-2.2.6.jar:na]
    at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85) [scalatest_2.11-2.2.6.jar:na]
    at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104) [scalatest_2.11-2.2.6.jar:na]
    at org.scalatest.Transformer.apply(Transformer.scala:22) [scalatest_2.11-2.2.6.jar:na]
    at org.scalatest.Transformer.apply(Transformer.scala:20) [scalatest_2.11-2.2.6.jar:na]
    at org.scalatest.FunSpecLike$$anon$1.apply(FunSpecLike.scala:422) [scalatest_2.11-2.2.6.jar:na]
    at org.scalatest.Suite$class.withFixture(Suite.scala:1122) [scalatest_2.11-2.2.6.jar:na]
    at org.scalatest.FunSpec.withFixture(FunSpec.scala:1626) [scalatest_2.11-2.2.6.jar:na]
    at org.scalatest.FunSpecLike$class.invokeWithFixture$1(FunSpecLike.scala:419) [scalatest_2.11-2.2.6.jar:na]
    at org.scalatest.FunSpecLike$$anonfun$runTest$1.apply(FunSpecLike.scala:431) [scalatest_2.11-2.2.6.jar:na]
    at org.scalatest.FunSpecLike$$anonfun$runTest$1.apply(FunSpecLike.scala:431) [scalatest_2.11-2.2.6.jar:na]
    at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306) [scalatest_2.11-2.2.6.jar:na]
    at org.scalatest.FunSpecLike$class.runTest(FunSpecLike.scala:431) [scalatest_2.11-2.2.6.jar:na]
    at org.scalatest.FunSpec.runTest(FunSpec.scala:1626) [scalatest_2.11-2.2.6.jar:na]
    at org.scalatest.FunSpecLike$$anonfun$runTests$1.apply(FunSpecLike.scala:464) [scalatest_2.11-2.2.6.jar:na]
    at org.scalatest.FunSpecLike$$anonfun$runTests$1.apply(FunSpecLike.scala:464) [scalatest_2.11-2.2.6.jar:na]
    at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:413) [scalatest_2.11-2.2.6.jar:na]
    at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:401) [scalatest_2.11-2.2.6.jar:na]
    at scala.collection.immutable.List.foreach(List.scala:381) [scala-library-2.11.7.jar:na]
    at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401) [scalatest_2.11-2.2.6.jar:na]
    at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:390) [scalatest_2.11-2.2.6.jar:na]
    at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:427) [scalatest_2.11-2.2.6.jar:na]
    at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:401) [scalatest_2.11-2.2.6.jar:na]
    at scala.collection.immutable.List.foreach(List.scala:381) [scala-library-2.11.7.jar:na]
    at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401) [scalatest_2.11-2.2.6.jar:na]
    at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:390) [scalatest_2.11-2.2.6.jar:na]
    at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:427) [scalatest_2.11-2.2.6.jar:na]
    at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:401) [scalatest_2.11-2.2.6.jar:na]
    at scala.collection.immutable.List.foreach(List.scala:381) [scala-library-2.11.7.jar:na]
    at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401) [scalatest_2.11-2.2.6.jar:na]
    at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:396) [scalatest_2.11-2.2.6.jar:na]
    at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:483) [scalatest_2.11-2.2.6.jar:na]
    at org.scalatest.FunSpecLike$class.runTests(FunSpecLike.scala:464) [scalatest_2.11-2.2.6.jar:na]
    at org.scalatest.FunSpec.runTests(FunSpec.scala:1626) [scalatest_2.11-2.2.6.jar:na]
    at org.scalatest.Suite$class.run(Suite.scala:1424) [scalatest_2.11-2.2.6.jar:na]
    at org.scalatest.FunSpec.org$scalatest$FunSpecLike$$super$run(FunSpec.scala:1626) [scalatest_2.11-2.2.6.jar:na]
    at org.scalatest.FunSpecLike$$anonfun$run$1.apply(FunSpecLike.scala:468) [scalatest_2.11-2.2.6.jar:na]
    at org.scalatest.FunSpecLike$$anonfun$run$1.apply(FunSpecLike.scala:468) [scalatest_2.11-2.2.6.jar:na]
    at org.scalatest.SuperEngine.runImpl(Engine.scala:545) [scalatest_2.11-2.2.6.jar:na]
    at org.scalatest.FunSpecLike$class.run(FunSpecLike.scala:468) [scalatest_2.11-2.2.6.jar:na]
    at org.scalatest.FunSpec.run(FunSpec.scala:1626) [scalatest_2.11-2.2.6.jar:na]
    at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:357) [scalatest_2.11-2.2.6.jar:na]
    at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:502) [scalatest_2.11-2.2.6.jar:na]
    at sbt.ForkMain$Run$2.call(ForkMain.java:296) [test-agent-0.13.9.jar:0.13.9]
    at sbt.ForkMain$Run$2.call(ForkMain.java:286) [test-agent-0.13.9.jar:0.13.9]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_20]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_20]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_20]
    at java.lang.Thread.run(Thread.java:745) [na:1.8.0_20]
[info]   - should not fail *** FAILED ***
[info]     java.lang.IllegalStateException: Connection pool is not yet initialized.(name:'default)
[info]     at scalikejdbc.ConnectionPool$$anonfun$get$1.apply(ConnectionPool.scala:57)
[info]     at scalikejdbc.ConnectionPool$$anonfun$get$1.apply(ConnectionPool.scala:55)
[info]     at scala.Option.getOrElse(Option.scala:121)
[info]     at scalikejdbc.ConnectionPool$.get(ConnectionPool.scala:55)
[info]     at scalikejdbc.ConnectionPool$.apply(ConnectionPool.scala:46)
[info]     at com.m3.octoparts.support.db.RequiresDB$class.flyway(RequiresDB.scala:57)
[info]     at com.m3.octoparts.database.MigrationsSpec.flyway$lzycompute(MigrationsSpec.scala:6)
[info]     at com.m3.octoparts.database.MigrationsSpec.flyway(MigrationsSpec.scala:6)
[info]     at com.m3.octoparts.support.db.RequiresDB$class.migrate(RequiresDB.scala:87)
[info]     at com.m3.octoparts.database.MigrationsSpec.migrate(MigrationsSpec.scala:6)
[info]     at com.m3.octoparts.database.MigrationsSpec$$anonfun$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcV$sp$2.apply$mcV$sp(MigrationsSpec.scala:12)
[info]     at com.m3.octoparts.database.MigrationsSpec$$anonfun$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcV$sp$2.apply(MigrationsSpec.scala:10)
[info]     at com.m3.octoparts.database.MigrationsSpec$$anonfun$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcV$sp$2.apply(MigrationsSpec.scala:10)
[info]     at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)
[info]     at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[info]     at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]     at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]     at org.scalatest.Transformer.apply(Transformer.scala:20)
[info]     at org.scalatest.FunSpecLike$$anon$1.apply(FunSpecLike.scala:422)
[info]     at org.scalatest.Suite$class.withFixture(Suite.scala:1122)
[info]     at org.scalatest.FunSpec.withFixture(FunSpec.scala:1626)
[info]     at org.scalatest.FunSpecLike$class.invokeWithFixture$1(FunSpecLike.scala:419)
[info]     at org.scalatest.FunSpecLike$$anonfun$runTest$1.apply(FunSpecLike.scala:431)
[info]     at org.scalatest.FunSpecLike$$anonfun$runTest$1.apply(FunSpecLike.scala:431)
[info]     at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)
[info]     at org.scalatest.FunSpecLike$class.runTest(FunSpecLike.scala:431)
[info]     at org.scalatest.FunSpec.runTest(FunSpec.scala:1626)
[info]     at org.scalatest.FunSpecLike$$anonfun$runTests$1.apply(FunSpecLike.scala:464)
[info]     at org.scalatest.FunSpecLike$$anonfun$runTests$1.apply(FunSpecLike.scala:464)
[info]     at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:413)
[info]     at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:401)
[info]     at scala.collection.immutable.List.foreach(List.scala:381)
[info]     at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
[info]     at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:390)
[info]     at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:427)
[info]     at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:401)
[info]     at scala.collection.immutable.List.foreach(List.scala:381)
[info]     at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
[info]     at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:390)
[info]     at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:427)
[info]     at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:401)
[info]     at scala.collection.immutable.List.foreach(List.scala:381)
[info]     at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
[info]     at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:396)
[info]     at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:483)
[info]     at org.scalatest.FunSpecLike$class.runTests(FunSpecLike.scala:464)
[info]     at org.scalatest.FunSpec.runTests(FunSpec.scala:1626)
[info]     at org.scalatest.Suite$class.run(Suite.scala:1424)
[info]     at org.scalatest.FunSpec.org$scalatest$FunSpecLike$$super$run(FunSpec.scala:1626)
[info]     at org.scalatest.FunSpecLike$$anonfun$run$1.apply(FunSpecLike.scala:468)
[info]     at org.scalatest.FunSpecLike$$anonfun$run$1.apply(FunSpecLike.scala:468)
[info]     at org.scalatest.SuperEngine.runImpl(Engine.scala:545)
[info]     at org.scalatest.FunSpecLike$class.run(FunSpecLike.scala:468)
[info]     at org.scalatest.FunSpec.run(FunSpec.scala:1626)
[info]     at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:357)
[info]     at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:502)
[info]     at sbt.ForkMain$Run$2.call(ForkMain.java:296)
[info]     at sbt.ForkMain$Run$2.call(ForkMain.java:286)
[info]     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[info]     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[info]     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[info]     at java.lang.Thread.run(Thread.java:745)
[info]   from a fully migrated database
[info]   - should not fail *** FAILED ***
[info]     java.lang.IllegalStateException: Connection pool is not yet initialized.(name:'default)
[info]     at scalikejdbc.ConnectionPool$$anonfun$get$1.apply(ConnectionPool.scala:57)
[info]     at scalikejdbc.ConnectionPool$$anonfun$get$1.apply(ConnectionPool.scala:55)
[info]     at scala.Option.getOrElse(Option.scala:121)
[info]     at scalikejdbc.ConnectionPool$.get(ConnectionPool.scala:55)
[info]     at scalikejdbc.ConnectionPool$.apply(ConnectionPool.scala:46)
[info]     at com.m3.octoparts.support.db.RequiresDB$class.flyway(RequiresDB.scala:57)
[info]     at com.m3.octoparts.database.MigrationsSpec.flyway$lzycompute(MigrationsSpec.scala:6)
[info]     at com.m3.octoparts.database.MigrationsSpec.flyway(MigrationsSpec.scala:6)
[info]     at com.m3.octoparts.support.db.RequiresDB$class.migrate(RequiresDB.scala:87)
[info]     at com.m3.octoparts.database.MigrationsSpec.migrate(MigrationsSpec.scala:6)
[info]     at com.m3.octoparts.database.MigrationsSpec$$anonfun$1$$anonfun$apply$mcV$sp$3$$anonfun$apply$mcV$sp$4.apply$mcV$sp(MigrationsSpec.scala:18)
[info]     at com.m3.octoparts.database.MigrationsSpec$$anonfun$1$$anonfun$apply$mcV$sp$3$$anonfun$apply$mcV$sp$4.apply(MigrationsSpec.scala:17)
[info]     at com.m3.octoparts.database.MigrationsSpec$$anonfun$1$$anonfun$apply$mcV$sp$3$$anonfun$apply$mcV$sp$4.apply(MigrationsSpec.scala:17)
[info]     at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)
[info]     at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[info]     at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]     at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]     at org.scalatest.Transformer.apply(Transformer.scala:20)
[info]     at org.scalatest.FunSpecLike$$anon$1.apply(FunSpecLike.scala:422)
[info]     at org.scalatest.Suite$class.withFixture(Suite.scala:1122)
[info]     at org.scalatest.FunSpec.withFixture(FunSpec.scala:1626)
[info]     at org.scalatest.FunSpecLike$class.invokeWithFixture$1(FunSpecLike.scala:419)
[info]     at org.scalatest.FunSpecLike$$anonfun$runTest$1.apply(FunSpecLike.scala:431)
[info]     at org.scalatest.FunSpecLike$$anonfun$runTest$1.apply(FunSpecLike.scala:431)
[info]     at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)
[info]     at org.scalatest.FunSpecLike$class.runTest(FunSpecLike.scala:431)
[info]     at org.scalatest.FunSpec.runTest(FunSpec.scala:1626)
[info]     at org.scalatest.FunSpecLike$$anonfun$runTests$1.apply(FunSpecLike.scala:464)
[info]     at org.scalatest.FunSpecLike$$anonfun$runTests$1.apply(FunSpecLike.scala:464)
[info]     at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:413)
[info]     at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:401)
[info]     at scala.collection.immutable.List.foreach(List.scala:381)
[info]     at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
[info]     at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:390)
[info]     at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:427)
[info]     at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:401)
[info]     at scala.collection.immutable.List.foreach(List.scala:381)
[info]     at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
[info]     at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:390)
[info]     at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:427)
[info]     at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:401)
[info]     at scala.collection.immutable.List.foreach(List.scala:381)
[info]     at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
[info]     at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:396)
[info]     at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:483)
[info]     at org.scalatest.FunSpecLike$class.runTests(FunSpecLike.scala:464)
[info]     at org.scalatest.FunSpec.runTests(FunSpec.scala:1626)
[info]     at org.scalatest.Suite$class.run(Suite.scala:1424)
[info]     at org.scalatest.FunSpec.org$scalatest$FunSpecLike$$super$run(FunSpec.scala:1626)
[info]     at org.scalatest.FunSpecLike$$anonfun$run$1.apply(FunSpecLike.scala:468)
[info]     at org.scalatest.FunSpecLike$$anonfun$run$1.apply(FunSpecLike.scala:468)
[info]     at org.scalatest.SuperEngine.runImpl(Engine.scala:545)
[info]     at org.scalatest.FunSpecLike$class.run(FunSpecLike.scala:468)
[info]     at org.scalatest.FunSpec.run(FunSpec.scala:1626)
[info]     at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:357)
[info]     at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:502)
[info]     at sbt.ForkMain$Run$2.call(ForkMain.java:296)
[info]     at sbt.ForkMain$Run$2.call(ForkMain.java:286)
[info]     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[info]     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[info]     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[info]     at java.lang.Thread.run(Thread.java:745)
[info] ScalaTest
[info] Run completed in 8 seconds, 752 milliseconds.
[info] Total number of tests run: 2
[info] Suites: completed 1, aborted 0
[info] Tests: succeeded 0, failed 2, canceled 0, ignored 0, pending 0
[info] *** 2 TESTS FAILED ***
```

### PR DESCRIPTION
**Pull request by lloydmeta**
RequiresDB itself is now private to the test-time "support" package,
because it has an implicit dependency on being run in a test suite that
ensures there is a Play app running before its commands are run.

### CODE REVIEW

**Comment by xevix** [comment]
> I felt it was appropriate to have PlayAppSupport extend RequiresDB because our app ... requires a DB to run..

Terrible logic. Rejected. :laughing: 

Thanks for the quick fix. It's odd I didn't run into this earlier, not sure why that is.

This now leads to some other issues. The vagrant box is up, but getting some odd exceptions from loggers.

```
[info] Run completed in 35 seconds, 78 milliseconds.
[info] Total number of tests run: 161
[info] Suites: completed 32, aborted 19
[info] Tests: succeeded 159, failed 2, canceled 0, ignored 0, pending 0
[info] *** 19 SUITES ABORTED ***
[info] *** 2 TESTS FAILED ***
[error] Error: Total 180, Failed 2, Errors 19, Passed 159
[error] Failed tests:
[error]     com.m3.octoparts.cache.MemoryBufferingRawCacheSpec
[error]     com.m3.octoparts.aggregator.service.PartRequestServiceSpec
[error] Error during tests:
[error]     controllers.system.BuildInfoControllerSpec
[error]     com.m3.octoparts.wiring.assembling.EnvConfigLoaderSpec
[error]     controllers.PartsControllerSpec
[error]     controllers.support.AuthenticationCheckSupportSpec
[error]     integration.ApplicationSpec
[error]     com.m3.octoparts.repository.ConfigImporterSpec
[error]     com.m3.octoparts.util.OctoMetricsImplSpec
[error]     controllers.support.DummyPrincipalSupportSpec
[error]     controllers.support.HttpPartConfigCheckerSpec
[error]     com.m3.octoparts.repository.config.CacheGroupRepositorySpec
[error]     integration.ApiSpec
[error]     com.m3.octoparts.database.MigrationsSpec
[error]     controllers.support.AuthorizationCheckSupportSpec
[error]     integration.AdminSpec
[error]     com.m3.octoparts.repository.DBConfigsRepositorySpec
[error]     controllers.AdminControllerSpec
[error]     controllers.system.HealthcheckControllerSpec
[error]     com.m3.octoparts.repository.config.HttpPartConfigRepositorySpec
[error]     controllers.system.SystemConfigControllerSpec
[error] (octoparts/test:test) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 144 s, completed Feb 9, 2016 11:40:53 AM
```

An example, but they're all roughly the same

```
[info] ApiSpec:
[info] Exception encountered when attempting to run a suite with class name: integration.ApiSpec *** ABORTED ***
[info]   java.lang.ClassCastException: org.slf4j.helpers.SubstituteLogger cannot be cast to ch.qos.logback.classic.Logger
[info]   at com.kenshoo.play.metrics.MetricsImpl.setupLogbackMetrics(Metrics.scala:63)
[info]   at com.kenshoo.play.metrics.MetricsImpl.onStart(Metrics.scala:73)
[info]   at com.m3.octoparts.util.OctoMetricsImpl.onStart(OctoMetricsImpl.scala:25)
[info]   at com.kenshoo.play.metrics.MetricsImpl.<init>(Metrics.scala:83)
[info]   at com.m3.octoparts.util.OctoMetricsImpl.<init>(OctoMetricsImpl.scala:17)
[info]   at com.m3.octoparts.wiring.UtilsModule$class.metrics(UtilsModule.scala:29)
[info]   at com.m3.octoparts.wiring.assembling.ApplicationComponents.metrics$lzycompute(ApplicationComponents.scala:23)
```

**Comment by mauhiz** [comment]
flip this : https://github.com/kenshoo/metrics-play/blob/master/src/main/scala/com/kenshoo/play/metrics/Metrics.scala#L36

**Comment by lloydmeta** [comment]
> It's odd I didn't run into this earlier, not sure why that is.

I am only able to get the previous errors if I use `testOnly`, in which case the ConnectionPool stateful singleton wasn't set up yet by earlier tests that initialise the app ;p

Not sure how you're getting these current errors though.

> flip this 

I think that is the culprit but since I can't reproduce the errors, I don't know why it works. Assuming that is the cause, since we have a custom implementation anyways, we can just override that member and make it default to false.

**Comment by xevix** [comment]
Ok, I can't reproduce this when running `sbt test` from the Vagrant machine; only from the host box. Did you try running tests from the host rather than the Vagrant machine?

**Comment by xevix** [comment]
There are some errors that are only showing up if I run all tests with `sbt test` and don't if I run the offending test with testOnly. Example:

```
[info] MemoryBufferingRawCacheSpec:
SLF4J: The following set of substitute loggers may have been accessed
SLF4J: during the initialization phase. Logging calls during this
SLF4J: phase were not honored. However, subsequent logging calls to these
SLF4J: loggers will work as normally expected.
SLF4J: See also http://www.slf4j.org/codes.html#substituteLogger
SLF4J: application
[info] - should store data for a while *** FAILED ***
[info]   None was not equal to Some("DEF") (MemoryBufferingRawCacheSpec.scala:26)
[info]   org.scalatest.exceptions.TestFailedException:
[info]   at org.scalatest.MatchersHelper$.newTestFailedException(MatchersHelper.scala:160)
[info]   at org.scalatest.Matchers$ShouldMethodHelper$.shouldMatcher(Matchers.scala:6254)
[info]   at org.scalatest.Matchers$AnyShouldWrapper.should(Matchers.scala:6288)

```

**Comment by lloydmeta** [comment]
> Ok, I can't reproduce this when running sbt test from the Vagrant machine; only from the host box. Did you try running tests from the host rather than the Vagrant machine?

I generally only run tests from the host, usually with `activator`, then `test` from within the SBT console.  However, I just tried variations of `sbt` then `test`,  `sbt test` from both the host (also tried `activator` variations here) and the VM and couldn't reproduce the errors.

**Comment by xevix** [comment]
@lloydmeta Dang. It's 100% reproducible here, even after doing a full `vagrant halt` and `vagrant up`. Will try to reproduce on another machine later.

**Comment by mauhiz** [comment]
It looks like that there are several implementation of slf4j on the classpath...?

**Comment by lloydmeta** [comment]
> It looks like that there are several implementation of slf4j on the classpath...?

/me crawls into a hole.

@mauhiz if you have time, mind giving running the tests on your machine ?

**Comment by mauhiz** [comment]
I wanted to. I just tried to `vagrant up`, but it failed provisioning with this message: 

> Unexpected Exception: global name 'display' is not defined

Any idea?

```
Vagrant 1.7.4
ansible 2.0.0.2
Python 2.7.11
```

**Comment by lloydmeta** [comment]
Strange, I wonder if it's related to this: https://github.com/ansible/ansible/issues/14147

My versions are:

```
Vagrant 1.7.4
ansible 1.8.2
Python 2.7.11
```

**Comment by mauhiz** [comment]
I downgraded ansible to `1.8.4` and provisioning now works. :game_die: 

Can ignore the following failure?

```
TASK: [td_agent | Check for fluent-plugin-elasticsearch gem] ****************** 
failed: [default] => {"changed": true, "cmd": "/usr/lib64/fluent/ruby/bin/fluent-gem list fluent-plugin-elasticsearch -i", "delta": "0:00:00.133794", "end": "2016-02-10 01:02:12.023123", "rc": 1, "start": "2016-02-10 01:02:11.889329", "warnings": []}
stdout: false
...ignoring
```

**Comment by mauhiz** [comment]
Besides this well-known test failure  :

```
[info] RichFutureWithTiming
[info] - should not start measuring too early *** FAILED ***
[info]   A timeout occurred waiting for a future to complete. Queried 11 times, sleeping 15 milliseconds between each query. (RichFutureWithTimingSpec.scala:43)
```

Test suite passed fine.

**Comment by lloydmeta** [comment]
@mauhiz thanks. added a longer `PatienceConfig` to deal with that one in c0fcf7a once and for all :smile: 

The rabbit hole gets deeper, as neither you nor I can reproduce the error..

**Comment by xevix** [comment]
@lloydmeta The change in PatienceConfig seems not to apply to testing, as I'm still experiencing timeouts with the default wait time error.

```
[info] PartRequestServiceSpec:
[info] #responseFor
[info]   when given a PartRequest with a partId that is not supported
11:57:34.363 [ForkJoinPool-1-worker-7] WARN  c.m.o.w.OctoClientSpec$$anonfun$1$$anon$1 - Unexpected response status: 'null' for path whatever
11:57:34.521 [ForkJoinPool-1-worker-7] WARN  c.m.o.w.OctoClientSpec$$anonfun$1$$anon$1 - Unexpected response status: 'null' for path whatever
11:57:34.676 [ForkJoinPool-1-worker-7] WARN  c.m.o.w.OctoClientSpec$$anonfun$1$$anon$1 - Unexpected response status: 'null' for path whatever
[info]   - should return a Future[PartResponse] with an error that mentions that the part Id is not supported *** FAILED ***
[info]     A timeout occurred waiting for a future to complete. Queried 10 times, sleeping 15 milliseconds between each query. (PartRequestServiceSpec.scala:42)
[info]     org.scalatest.concurrent.Futures$FutureConcept$$anon$1:
[info]     at org.scalatest.concurrent.Futures$FutureConcept$class.tryTryAgain$1(Futures.scala:546)
[info]     at org.scalatest.concurrent.Futures$FutureConcept$class.futureValue(Futures.scala:558)
[info]     at org.scalatest.concurrent.ScalaFutures$$anon$1.futureValue(ScalaFutures.scala:74)
[info]     at org.scalatest.concurrent.Futures$class.whenReady(Futures.scala:684)
[info]     at com.m3.octoparts.aggregator.service.PartRequestServiceSpec.whenReady(PartRequestServiceSpec.scala:19)
```

**Comment by lloydmeta** [comment]
@xevix I fixed it for that particular test suite.

`PartRequestServiceSpec` (and `RichFutureWithTimingSpec` for that matter) have never failed locally for me nor on Travis' free testing infrastructure due to timeouts; and they shouldn't because neither do any form of I/O or intense computing. Under those circumstances, the default PatienceConfig for testing futures that comes with Scalatest should be sufficient.

One cause could be too many things vying for computing resources on your machine at the same time during tests?

**Comment by xevix** [comment]
@lloydmeta Ok something is definitely odd. I noticed there are long pauses in waiting for ForkJoinPool workers. I manually ran tests with a scale of 5x and it still wasn't enough. My machine isn't running anything CPU-intensive other than this, so I wonder if there's an issue with threadswitching somehow.

```
> testOnly -- -F 5
... snip ...

[info] PartRequestServiceSpec:
12:30:25.970 [ForkJoinPool-1-worker-5] WARN  c.m.o.w.OctoClientSpec$$anonfun$1$$anon$1 - Unexpected response status: 'null' for path whatever
[info] #responseFor
[info]   when given a PartRequest with a partId that is not supported
12:30:26.008 [ForkJoinPool-1-worker-5] WARN  c.m.o.w.OctoClientSpec$$anonfun$1$$anon$1 - Unexpected response status: 'null' for path whatever
12:30:26.765 [ForkJoinPool-1-worker-5] WARN  c.m.o.w.OctoClientSpec$$anonfun$1$$anon$1 - Unexpected response status: 'null' for path whatever
[info]   - should return a Future[PartResponse] with an error that mentions that the part Id is not supported *** FAILED ***
[info]     A timeout occurred waiting for a future to complete. Queried 11 times, sleeping 75 milliseconds between each query. (PartRequestServiceSpec.scala:42)
```

**Comment by xevix** [comment]
With a scale of 10x all tests are passing, and the logging issue goes away. So it seems that whatever the cause of the Future timeouts, the Future timeouts are somehow related to triggering the logging issues.

**Comment by xevix** [comment]
Since the initial issue this PR is addressing has been resolved, merging. Thanks!

**Comment by lloydmeta** [comment]
@xevix interesting find. Also, didn't know about that flag !

**Comment by xevix** [comment]
@lloydmeta http://www.scalatest.org/user_guide/using_the_runner#scalingTimeSpans

**Comment by lloydmeta** [comment]
:+1:

**Pull request merged**
