### PR TITLE
Upgrade scala, sbt and some sbt plugins

### PR DESCRIPTION
**Pull request by seratch**
This pull request fixes the issues below:
- Upgrading oudated sbt version
  - from 0.13.9 to 0.13.12
  - The `Build` trait is deprecated since 0.13.12 and will be removed in 1.0 (see also https://github.com/sbt/sbt/releases/tag/v0.13.12, https://github.com/sbt/sbt/pull/2530)
- Upgrading outdated scoverage, coveralls plugin
  - Travis builds sometimes look unstable, I hope this upgrade makes the situation better
  - Upgrading other sbt plugins brings more changes, I'll work on them in another pull requests
- Upgrading Scala patch version
  - from 2.11.7 to 2.11.8
  - Fix release scripts as well

### CODE REVIEW

**Comment by seratch** [comment]
I've upgraded scoverage version to the latest but the tests still occasionally fail on TravisCI although they never fail on my local machine. I reran the job and it succeeded then.

**Review by lloydmeta — COMMENTED** [review]
Looks reasonable to me. Sadly without any recovered logs of the supposed failed builds on TravisCI, it's hard to figure out what their causes might have been.

**Comment by seratch** [comment]
Ah, indeed, I should have saved the outputs... I'll save the failures next time.

**Review by btakashi — APPROVED** [review]
I think these changes look fine.

**Comment by btakashi** [comment]
(Ah, perhaps I don't have the authority to approve the request, in the future I'll leave that up to others)

**Pull request merged**
