### PR TITLE
Rework the AggregateResponse enrichments

### LINKED ISSUE #90: RichAggregateResponse should not try to extract JSON from a failed part response
e.g. if partResponse.errors.nonEmpty => print the errors, return None

### PR DESCRIPTION
**Pull request by mauhiz**
Fixes #90 

- Added a `RichPartResponse` and useful methods to it
- removed the `recoverWith` scheme. Users should prefer `tryJsonPart`.
- Print warnings

### CODE REVIEW

**Comment by lloydmeta** [comment]
Nice job. Thanks for updating the Scala client sample as well.

Please add:

- tests for the RichPartResponse methods
- Scaladocs for the RichPartResponse methods

**Comment by mauhiz** [comment]
Done. I skipped methods that were already tested in `RichAggregateResponseSpec`

**Comment by lloydmeta** [comment]
Currently fails to compile :( https://travis-ci.org/m3dev/octoparts/builds/50430642#L423

**Comment by mauhiz** [comment]
Sorry, that push was a tad too early.

**Pull request merged**
