### PR TITLE
Feature/list endpoint support. Relates to #84

### PR DESCRIPTION
**Pull request by lloydmeta**
Related: #84 

- Fixes the Swagger annotation
- Adds support for filtering endpoint listing by part id

### CODE REVIEW

**Comment by mauhiz** [comment]
Why rename the param ? This risks breaking stuff for users

**Comment by lloydmeta** [comment]
> Why rename the param ? This risks breaking stuff for users

Which param did I rename?

**Comment by mauhiz** [comment]
partId -> partIdParams. I agree there was a mismatch between the route and the action  method

**Comment by lloydmeta** [comment]
> partId -> partIdParams. I agree there was a mismatch between the route and the action method

No, I didn't change the action parameter name nor the route file, they were both `partIdParams`. 

What was changed was the annotation for that action (it never worked), and the new annotation correctly has `partIdParams` as the name.

**Comment by mauhiz** [comment]
Oh I see thanks. This API is called for exporting a single part I think - so it should keep working like this. LGTM :+1:

**Pull request merged**
